### ISSUE TITLE
Index update task cant follow redirects

### ISSUE THREAD

**Issue by Cookies4Sale** [pagemachine/searchable#31]
Thank you for this helpful extension.
I have set up this extension on my local machine with a Elasticsearch service in a docker container with success.
Now i tried to run this extension on a server but i got this error while executing the Index:update:full command:

Issue:
Oops, an error occurred!

Return value of PAGEmachine\Searchable\LinkBuilder\Frontend\FrontendRequest::send() must be of the type array, null returned

Platforms:
Typo3 10.4.14, PHP 7.4, Elasticsearch 7.11.2

Description:
The FrontendRequest Class uses the GuzzleClient from Typo3 in his request. But this request returns no data if the request Url is redirected (301) from the Server. Therefore i had to add 'allow_redirects' as options to the request. This way the request follows the redirection and returns the data as expected.

Solution:
The Issue could be resolved by adding a strict redirect setting to the GuzzleClient in the FrontentRequest Class via a composer patch. I saw this solution here: https://medium.com/wine-in-black-tech/configure-guzzle-to-follow-redirects-and-keep-post-data-ff0098d7dc63

Composer patch:
```
Index: Classes/LinkBuilder/Frontend/FrontendRequest.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- Classes/LinkBuilder/Frontend/FrontendRequest.php	(revision ce344e6ee2353e179478a90c4ecba025b736b661)
+++ Classes/LinkBuilder/Frontend/FrontendRequest.php	(date 1618213581846)
@@ -29,6 +29,9 @@
                     'configurations' => $linkConfigurations,
                 ],
                 'http_errors' => false,
+                'allow_redirects' => [
+                    'strict' => true
+                ]
             ]
         );
         // \TYPO3\CMS\Extbase\Utility\DebuggerUtility::var_dump((string)$response->getBody(), __METHOD__, 8, defined('TYPO3_cliMode') || defined('TYPO3_REQUESTTYPE') && (TYPO3_REQUESTTYPE & TYPO3_REQUESTTYPE_CLI));
```

**Comment by mbrodala** [comment]
Can you explain what redirect occurs here? At least TYPO3 or this extension won't do a redirect by default.

**Comment by schliesser** [comment]
The problem is this redirect in the .htaccess:

```
# redirect non-trailing slash to trailing slash
# https://stackoverflow.com/questions/21417263/htaccess-add-remove-trailing-slash-from-url
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^([^.]*[^/])$ /$1/ [L,R=301]
```

**Comment by schliesser** [comment]
Solved by excluding the request url:

```apache
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_URI} !^/-/searchable/urls$
RewriteRule ^([^.]*[^/])$ /$1/ [L,R=301]
```

**Comment by mbrodala** [comment]
Yes, this looks like the best solution for custom code. Our request handling should not try to silently cover things like these, otherwise we may unintentionally swallow errors.
